{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opencord.fullname" . }}
  labels:
    {{- include "opencord.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if or .Values.ingress.tls (and .Values.customDomains.enabled .Values.customDomains.tlsSecretName .Values.customDomains.hosts) }}
  tls:
    {{- with .Values.ingress.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.customDomains.enabled .Values.customDomains.tlsSecretName .Values.customDomains.hosts }}
    - secretName: {{ .Values.customDomains.tlsSecretName | quote }}
      hosts:
        {{- range .Values.customDomains.hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- $serviceValues := index $.Values .service }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "opencord.componentName" (dict "root" $ "component" .service) }}
                port:
                  number: {{ $serviceValues.servicePort }}
          {{- end }}
    {{- end }}
    {{- if .Values.customDomains.enabled }}
    {{- range .Values.customDomains.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "opencord.componentName" (dict "root" $ "component" "api") }}
                port:
                  number: {{ $.Values.api.servicePort }}
          - path: /gateway
            pathType: Prefix
            backend:
              service:
                name: {{ include "opencord.componentName" (dict "root" $ "component" "realtime") }}
                port:
                  number: {{ $.Values.realtime.servicePort }}
    {{- end }}
    {{- end }}
{{- end }}
