apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencord.componentName" (dict "root" . "component" "worker") }}
  labels:
    {{- include "opencord.componentLabels" (dict "root" . "component" "worker") | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "opencord.componentSelectorLabels" (dict "root" . "component" "worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opencord.componentSelectorLabels" (dict "root" . "component" "worker") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "opencord.serviceAccountName" . }}
      containers:
        - name: worker
          image: {{ include "opencord.image" (dict "root" . "repository" .Values.worker.image.repository) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.external.urlSecretName | quote }}
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.external.urlSecretName | quote }}
                  key: REDIS_URL
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
