name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: azure/setup-helm@v4
      - run: helm lint charts/opencord
      - run: helm template opencord charts/opencord
