database:
  image:
    repository: "timescale/timescaledb"
    tag: "2.28.1-pg18-oss"
  external:
    enabled: true
    urlSecretName: "opencord-database"

kafka:
  bootstrapServers:
    - "kafka.chat.example.com:9092"

scylla:
  contactPoints:
    - "scylla.chat.example.com:9042"
  keyspace: "opencord"

objectStorage:
  provider: "s3"
  bucket: "opencord"
  endpoint: "https://s3.example.com"
  existingSecret: "opencord-s3"
